version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 5
    target-branch: main
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/orchestration-stub/src"
    open-pull-requests-limit: 10
    groups:
      npm-babel-dependencies:
        patterns:
          - "@babel/*"
      npm-eslint-dependencies:
        patterns:
          - "*eslint*"
    target-branch: main
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/ipv-stub/src"
    open-pull-requests-limit: 10
    groups:
      npm-eslint-dependencies:
        patterns:
          - "*eslint*"
    target-branch: main
    schedule:
      interval: daily