version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 5
    target-branch: main
    schedule:
      interval: daily
      time: "03:00"
  - package-ecosystem: npm
    directory: "/orchestration-stub"
    open-pull-requests-limit: 10
    groups:
      npm-babel-dependencies:
        patterns:
          - "@babel/*"
      npm-eslint-dependencies:
        patterns:
          - "*eslint*"
    target-branch: main
    schedule:
      interval: daily
      time: "03:00"
  - package-ecosystem: npm
    directory: "/ipv-stub"
    open-pull-requests-limit: 10
    groups:
      npm-eslint-dependencies:
        patterns:
          - "*eslint*"
    target-branch: main
    schedule:
      interval: daily
      time: "03:00"