AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AMC Authentication Stub

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs22.x
    Architectures:
      - x86_64

Parameters:
  Environment:
    Type: String
    Default: dev

Mappings:
  EnvironmentConfiguration:
    dev:
      amcStubDomainName: amcstub.signin.dev.account.gov.uk
      hostedZoneId: "Z07405851J4NJYGEP1PS7"

    authdev1:
      amcStubDomainName: amcstub.signin.authdev1.dev.account.gov.uk
      hostedZoneId: "Z01488663SVMGDFYGEX88"

    authdev2:
      amcStubDomainName: amcstub.signin.authdev2.dev.account.gov.uk
      hostedZoneId: "Z0283478G72QVGV7VVBG"

    authdev3:
      amcStubDomainName: amcstub.signin.authdev3.dev.account.gov.uk
      hostedZoneId: "Z04928373OSDE66G6PJLG"

    build:
      amcStubDomainName: amcstub.signin.build.account.gov.uk
      hostedZoneId: "Z09720813AWZDQSXZBWKJ"

Resources:
  AMCAuthorizeStubFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: endpoints/amc-authorize.handler
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      Events:
        GetAuthorize:
          Type: Api
          Properties:
            Path: /authorize
            Method: GET
        PostAuthorize:
          Type: Api
          Properties:
            Path: /authorize
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/endpoints/amc-authorize.ts
        Minify: true
        Sourcemap: true
        Target: node22

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !FindInMap [ EnvironmentConfiguration, !Ref Environment, amcStubDomainName ]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !FindInMap [ EnvironmentConfiguration, !Ref Environment, amcStubDomainName ]
          HostedZoneId: !FindInMap [ EnvironmentConfiguration, !Ref Environment, hostedZoneId ]
