AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions
Description: AMC Authentication Stub

Globals:
  Function:
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    Timeout: 30
    Runtime: nodejs22.x
    Architectures:
      - x86_64

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - local
      - dev
      - build

  SubEnvironment:
    Type: String
    Description: >
      When deploying to dev, optionally configure which sub-environment to deploy to
      i.e. authdev1, authdev2. This feature is not available for route-to-live environments
    Default: none
    AllowedValues:
      - none
      - authdev1
      - authdev2
      - authdev3

  ArtifactSourceBucket:
    Type: String
    Default: none

  VpcStackName:
    Type: String
    Default: none

  BuildNotificationStackName:
    Type: String
    Default: none

  CodeSigningConfigArn:
    Type: String
    Default: none

  PermissionsBoundary:
    Type: String
    Default: none

  TestRoleArn:
    Type: String
    Default: none

  TrafficTestRoleArn:
    Type: String
    Default: none

  DisableCanaryAlarms:
    Type: String
    Default: "false"

Conditions:
  UseCodeSigning: !Not [!Equals [none, !Ref CodeSigningConfigArn]]
  UsePermissionsBoundary: !Not [!Equals [none, !Ref PermissionsBoundary]]
  UseSubEnvironment: !And
    - !Equals [!Ref Environment, dev]
    - !Not [!Equals [!Ref SubEnvironment, none]]
  IsLocalEnvironment: !Equals [!Ref Environment, local]

Mappings:
  EnvironmentConfiguration:
    dev:
      amcStubDomainName: amcstub.signin.dev.account.gov.uk
      hostedZoneId: "Z07405851J4NJYGEP1PS7"

    authdev1:
      amcStubDomainName: amcstub.signin.authdev1.dev.account.gov.uk
      hostedZoneId: "Z01488663SVMGDFYGEX88"

    authdev2:
      amcStubDomainName: amcstub.signin.authdev2.dev.account.gov.uk
      hostedZoneId: "Z0283478G72QVGV7VVBG"

    authdev3:
      amcStubDomainName: amcstub.signin.authdev3.dev.account.gov.uk
      hostedZoneId: "Z04928373OSDE66G6PJLG"

    build:
      amcStubDomainName: amcstub.signin.build.account.gov.uk
      hostedZoneId: "Z09720813AWZDQSXZBWKJ"

Resources:
  AMCAuthorizeStubFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: endpoints/amc-authorize.handler
      LoggingConfig:
        LogGroup: !Ref AMCAuthorizeStubFunctionLogGroup
      Environment:
        Variables:
          ENVIRONMENT: !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment]
          AMC_PRIVATE_ENCRYPTION_KEY: !If
            - IsLocalEnvironment
            - |
              -----BEGIN PRIVATE KEY-----
              MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCRD7zPmvBh4d1V
              m8c9CCx2CbvyI0VjmGq3Phic7umdWc110JUf7MJyrcYgehNC35yQS2teQKFgp8q+
              fGNzu+cRWNv7D1L4hOoK4ksLr6GDPYKx3u1NmxSNmd47OUTOdMI2A0HtH8ViglJU
              8PC3L9h50vvZm81+TUN7mEdJqNSK9q91Idv411GBtxsOT82GJROU+pWpWUm6nNGg
              I1eUgdL4VY8oEQ2ITwkAZ5/sHd5gb+ArKTghhvJkOXO4k88LhWUtEggdK7pMxTNQ
              tNWxwsOFqFW+KvEBWUZEpuMqEe4hwCDwdbJtdA5HKMhwQTuiBdvxpaFE+EIlXqGc
              3dFco7iLAgMBAAECggEANRKOcGBOCWnTClK7stsuNSN7lWwNI5KsnI1GAQiyBSVJ
              dAzTuoHrZHyqi9BOAr4AMJS/XBUGVfAdz9J/qmS5dhHOLg0dvJoYbNH9RfHEhFk5
              W21l4epWuzXr5jweLfDu60cG1EQ2+cMXb0dVspf5Oh0UkrmbldWb1njQwCTaWlq4
              slyH+wcqTu1UOKjX2lY0/2iPf4TIEhjedpFfDw884DQ/06HVbTFnTScYEUDeY1Tr
              JZxEs+8+KK69opCzR0303JN70nYyLkzHdvt64kZIQ8sGFzGsbIIQuGxLjTufJnrM
              sWEI4VbSShbyFxDfmMzaS6KoWWjZ8O0W+PrVwV6VNQKBgQDDPOjhbdv9tEeY+x9T
              6Ihcjl2pVXDx59iXJyG5IVtAO2IKaVG+QR3/H2P7/F/l9bgMBzWN5pjDSajfo05R
              YmWm2r9W4fT2KPHIU7T23hX0cg3B9QuyPqAVSl5ynxaG7pAM/UgzvlxTAFroRfcs
              iq1UPcAL/xs1timxFXIygcg+5QKBgQC+NSUvkWb3THyPCro2+E33LkVX57UJC/er
              AWnOUcWwOknrUTPw6Xk347YRDyB4zT/2PHCOsALsJVKUuG3H7XPEYVdm3Q5ek/7U
              8NmbTKwKLS/4z7Ts8X4hfyH3a8nM79m9OKt1+n0+d5l04sWfrEJhW4mB8okDmLOM
              zYEP5xgyrwKBgBbqMzsiNcvVOQIPl2G1zStv2jZhvNvnplg3U5HzBE7JqXwnWFzI
              L8kd2hJdULQg3vUqc3KwOgXRw2xcMnkC34Nx8Ts1UhcCPz6P9JF1B4alTFATfsfw
              6cEV9XfmjDJSFb4wjCTmltd3FzRj4drse+ODS+Mckgj/1GzgY4LiEKqxAoGAKiod
              1C2nZarO8eau4QCqR+E5/gKfXyIIBSCLE/GMoURKnp+hpAYdmQYhliaETEMzqqI7
              UWYzP6YGaHF55Jf+0cnCVksqpEyqcQnzMzoL6TWbLMzejqf6DfLg1LhQQ93npsqp
              N74PhYl9uyuKI5tMG8ju8p+RP/rZ0py7v4q7EoECgYBSWlumCv72JfsN+4/qdK0j
              5mn5N0rGiS8Zuw5IuZT0AnH4JYCYoiIe2TpgSLZJbYx+WzrASFp/EcIr7+DkxArZ
              4uWILIxYS+oErceaX8i0ZXDjz6l562Ig2z2nx7u0fAvZUbDz1+kyjQO1ofpSmJOz
              Dm3hJHTzvZdMgmWQ5J12oQ==
              -----END PRIVATE KEY-----
            - !If
              - UseSubEnvironment
              - !Sub '{{resolve:secretsmanager:/${SubEnvironment}/stubs/amc-stub-private-key}}'
              - !Sub '{{resolve:secretsmanager:/${Environment}/stubs/amc-stub-private-key}}'
          AUTH_PUBLIC_SIGNING_KEY_AMC_AUDIENCE: !If
            - IsLocalEnvironment
            - |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoghZfjgenZ1l0z4z8ShIJ+FxzgH2
              Y6wLyeUSbI3C5wQfPkoypnAaoBx/5dSH9zjE548rBG94z2gyRn8mrE7fqg==
              -----END PUBLIC KEY-----
            - !If
              - UseSubEnvironment
              - !Sub '{{resolve:secretsmanager:/${SubEnvironment}/stubs/amc-stub-public-key-amc-audience}}'
              - !Sub '{{resolve:secretsmanager:/${Environment}/stubs/amc-stub-public-key-amc-audience}}'
          AUTH_PUBLIC_SIGNING_KEY_AUTH_AUDIENCE: !If
            - IsLocalEnvironment
            - |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExaePS02o9rzy0+qyoDGDgKgEQ8DS
              Qbm8tgWxPnpIkj0pwXHuCm/ENPQRK4cM32T4crC9vArwIzys1lriZp47WA==
              -----END PUBLIC KEY-----
            - !If
              - UseSubEnvironment
              - !Sub '{{resolve:secretsmanager:/${SubEnvironment}/stubs/amc-stub-public-key-auth-audience}}'
              - !Sub '{{resolve:secretsmanager:/${Environment}/stubs/amc-stub-public-key-auth-audience}}'
      Events:
        GetAuthorize:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /authorize
            Method: GET
        PostAuthorize:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /authorize
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/endpoints/amc-authorize.ts
        Minify: true
        Sourcemap: true
        Target: node22

  AMCAuthorizeStubFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !If [UseSubEnvironment, !Sub "/aws/lambda/${SubEnvironment}-amc-stub-authorize", !Sub "/aws/lambda/${Environment}-amc-stub-authorize"]
      RetentionInDays: 30

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-ApiGateway
      StageName: Live
      AlwaysDeploy: true
      EndpointConfiguration: REGIONAL
      Tags:
        FMSRegionalPolicy: "false"
        CustomPolicy: "apistub"
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "Auth Team AMC Stub"
          version: "1.0"
        paths:
          /authorize:
            get:
              responses:
                "200":
                  description: OK
                  content:
                    application/json:
                      schema:
                        type: object
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AMCAuthorizeStubFunction.Arn}/invocations
                passThroughBehavior: "when_no_match"
                payloadFormatVersion: "2.0"
            post:
              responses:
                "200":
                  description: OK
                  content:
                    application/json:
                      schema:
                        type: object
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AMCAuthorizeStubFunction.Arn}/invocations
                passThroughBehavior: "when_no_match"
                payloadFormatVersion: "2.0"
        x-amazon-apigateway-policy:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal: "*"
              Action: "execute-api:Invoke"
              Resource: "*"

  GatewayDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !FindInMap [EnvironmentConfiguration, !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment], amcStubDomainName]
      RegionalCertificateArn: !Ref Certificate
      SecurityPolicy: TLS_1_2
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiGatewayMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: Certificate
    Properties:
      DomainName: !Ref GatewayDomain
      RestApiId: !Ref ApiGateway
      Stage: Live

  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !FindInMap [EnvironmentConfiguration, !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment], hostedZoneId]
      Type: A
      Name: !FindInMap [EnvironmentConfiguration, !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment], amcStubDomainName]
      AliasTarget:
        DNSName: !GetAtt GatewayDomain.RegionalDomainName
        HostedZoneId: !GetAtt GatewayDomain.RegionalHostedZoneId

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !FindInMap [EnvironmentConfiguration, !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment], amcStubDomainName]
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !FindInMap [EnvironmentConfiguration, !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment], amcStubDomainName]
          HostedZoneId: !FindInMap [EnvironmentConfiguration, !If [UseSubEnvironment, !Ref SubEnvironment, !Ref Environment], hostedZoneId]
