AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions
Description: Notify Stub

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs24.x
    Architectures:
      - x86_64

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - local

  CodeSigningConfigArn:
    Type: String
    Default: none

  PermissionsBoundary:
    Type: String
    Default: none

Conditions:
  UseSubEnvironment: !And
    - !Equals [!Ref Environment, dev]
    - !Not [!Equals [!Ref SubEnvironment, none]]
  IsLocalEnvironment: !Equals [!Ref Environment, local]

Mappings:
  EnvironmentConfiguration:
    local:
      notifyStubDomainName: localhost:3000
      protocol: http

Resources:
  NotifyStubApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-ApiGateway
      StageName: Live
      AlwaysDeploy: true
      EndpointConfiguration: REGIONAL
      Tags:
        FMSRegionalPolicy: "false"
        CustomPolicy: "apistub"
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "GOV.UK Notify Stub"
          version: "1.0"
        paths:
          /:
            get:
              responses:
                "200":
                  description: OK
                  content:
                    text/html:
                      schema:
                        type: string
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListNotificationsFunction.Arn}/invocations
                passThroughBehavior: "when_no_match"
                payloadFormatVersion: "2.0"
          /v2/notifications/sms:
            post:
              responses:
                "201":
                  description: Created
                  content:
                    application/json:
                      schema:
                        type: object
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendSmsFunction.Arn}/invocations
                passThroughBehavior: "when_no_match"
                payloadFormatVersion: "2.0"
        x-amazon-apigateway-policy:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal: "*"
              Action: "execute-api:Invoke"
              Resource: "*"

  ListNotificationsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${env}-notify-stub-list-notifications
        - env: !Ref Environment
      RetentionInDays: 30

  ListNotificationsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/endpoints/list-notifications.ts
    Properties:
      CodeUri: ./
      Handler: list-notifications.handler
      LoggingConfig:
        LogGroup: !Ref ListNotificationsFunctionLogGroup
      Events:
        ListNotifications:
          Type: Api
          Properties:
            RestApiId: !Ref NotifyStubApi
            Path: /
            Method: GET

  SendSmsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${env}-notify-stub-send-sms
        - env: !Ref Environment
      RetentionInDays: 30

  SendSmsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/endpoints/send-sms.ts
    Properties:
      CodeUri: ./
      Handler: send-sms.handler
      LoggingConfig:
        LogGroup: !Ref SendSmsFunctionLogGroup
      Environment:
        Variables:
          NOTIFICATIONS_TABLE_NAME: !Ref NotificationsTable
          NOTIFY_DOMAIN: !FindInMap [EnvironmentConfiguration, !Ref Environment, notifyStubDomainName]
          NOTIFY_PROTOCOL: !FindInMap [EnvironmentConfiguration, !Ref Environment, protocol]
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref NotificationsTable
      Events:
        SendSms:
          Type: Api
          Properties:
            RestApiId: !Ref NotifyStubApi
            Path: /v2/notifications/sms
            Method: POST

  NotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - ${env}-NotifyStub-Notifications
        - env: !Ref Environment
      KeySchema:
        - AttributeName: destination
          KeyType: HASH
        - AttributeName: notification_id
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: destination
          AttributeType: S
        - AttributeName: notification_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Name
          Value: NotifyStub-Notifications

Outputs:
  NotifyStubApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${NotifyStubApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/
