###
GET https://p4ftrlfigb.execute-api.eu-west-2.amazonaws.com/dev/.well-known/jwks.json

###
GET https://p4ftrlfigb.execute-api.eu-west-2.amazonaws.com/dev/.well-known/storage-token-jwk.json

### AUTHORIZE
GET https://ipvstub.signin.dev.account.gov.uk/authorize


### TOKEN
POST https://ipvstub.signin.dev.account.gov.uk/token
Content-Type: application/json

{
}

### REVERIFICATION
GET https://ipvstub.signin.dev.account.gov.uk/reverification
