version = 0.1

[authdev1.deploy.parameters]
stack_name = "authdev1-ipv-stub"
resolve_s3 = true
s3_prefix = "authdev1-ipv-stub"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"authdev1\""
image_repositories = []

[authdev2.deploy.parameters]
stack_name = "authdev2-ipv-stub"
resolve_s3 = true
s3_prefix = "authdev2-ipv-stub"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"authdev2\""
image_repositories = []

