AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - local
      - dev
      - build

Mappings:
  EnvironmentConfiguration:
    local:
      domain: none
    dev:
      domain: .dev.account.gov.uk

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      AlwaysDeploy: true

  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index/index.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          REDIS_URL: "ssm-placeholder"
          DOMAIN:
            !FindInMap [EnvironmentConfiguration, !Ref Environment, domain]
      Architectures:
        - arm64
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: get
        Post:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index/index.ts
        Minify: true
        Sourcemap: true
        Target: "es2020"

  CallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: callback/index.handler
      Runtime: nodejs20.x
      Environment:
        Variables:
          REDIS_URL: "ssm-placeholder"
          DOMAIN:
            !FindInMap [EnvironmentConfiguration, !Ref Environment, domain]
      Architectures:
        - arm64
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /orchestration-callback
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - callback/index.ts
        Minify: true
        Sourcemap: true
        Target: "es2020"
