name: Build and deploy AMC stub

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./amc-stub

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '22.12.0'

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133 # v2
        with:
          use-installer: true  # this caches installation but is only available on Linux x86-64 runners

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ secrets.AMC_STUB_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Install dependencies
        run: npm ci --ignore-scripts && echo "$PWD/node_modules/.bin" >> $GITHUB_PATH

      - name: SAM validate
        run: sam validate

      - name: SAM build and test
        run: sam build

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@5879c30205266ad61e8299a4fcea76364530c9c1 # v3.14.0
        with:
            artifact-bucket-name: ${{ secrets.AMC_STUB_ARTIFACT_BUCKET_NAME }}
            signing-profile-name: ${{ secrets.AMC_STUB_SIGNING_PROFILE_NAME }}
            working-directory: ./amc-stub/.aws-sam/build
