name: Build and deploy IPV stub

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./ipv-stub

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@f664fad9e12492edfc187a31f575537dfbb0ff63 # v2
        with:
          use-installer: true  # this caches installation but is only available on Linux x86-64 runners

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: ${{ secrets.IPV_STUB_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: SAM validate
        run: sam validate

      - name: SAM build and test
        run: sam build

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@fda75612a1b0e5a8c84ae7c44a23340e50e5bbde # v3.11.0
        with:
            artifact-bucket-name: ${{ secrets.IPV_STUB_ARTIFACT_BUCKET_NAME }}
            signing-profile-name: ${{ secrets.IPV_STUB_SIGNING_PROFILE_NAME }}
            working-directory: ./ipv-stub/.aws-sam/build
